# Generated by Django 4.1.9 on 2024-01-10 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("file_versions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="created_on",
            field=models.TextField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="file_binary",
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="file_url",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="owned_by",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="version_number",
            field=models.IntegerField(default=0),
        ),
    ]
