# Generated by Django 4.1.9 on 2024-01-10 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_fileversion_created_on_fileversion_file_binary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
